version: '3.9'

services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=messages_app
      - MYSQL_USER=messages_app
      - MYSQL_PASSWORD=12345
      - MYSQL_ROOT_PASSWORD=12345
      - TZ=UTC
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql